CookBook

--------第一章--------
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.8.0 -- An enhanced Interactive Python.

w=[1,1,1,2,2,3]

from collections import Counter

wc=Counter(w)

a=wc.most_common(2)

a
Out[5]: [(1, 3), (2, 2)]

wc.update()

wc
Out[7]: Counter({1: 3, 2: 2, 3: 1})

class User:
    def_init_(self,user_id)
    self.user_id=user_id
    def  _repr_(self):
        return 'User({})'.format(self.user_id)
        
Traceback (most recent call last):

  File "<ipython-input-8-c8b9ca250f7c>", line 1, in <module>
    class User:

  File "<ipython-input-8-c8b9ca250f7c>", line 2, in User
    def_init_(self,user_id)

NameError: name 'def_init_' is not defined




class User:
    def__init__(self,user_id)
    self.user_id=user_id
    def  __repr__(self):
        return 'User({})'.format(self.user_id)
        
Traceback (most recent call last):

  File "<ipython-input-9-7cd6e6810379>", line 1, in <module>
    class User:

  File "<ipython-input-9-7cd6e6810379>", line 2, in User
    def__init__(self,user_id)

NameError: name 'def__init__' is not defined




class User:
    def __init__(self,user_id)
    self.user_id=user_id
    def  __repr__(self):
        return 'User({})'.format(self.user_id)
  File "<ipython-input-10-894c834986f6>", line 2
    def __init__(self,user_id)
                              ^
SyntaxError: invalid syntax




class User:
    def __init__(self,user_id):
        self.user_id=user_id
    def  __repr__(self):
        return 'User({})'.format(self.user_id)
        

users=[User(23),user(3),User(99)]
Traceback (most recent call last):

  File "<ipython-input-12-7645bd143d45>", line 1, in <module>
    users=[User(23),user(3),User(99)]

NameError: name 'user' is not defined




users=[User(23),User(3),User(99)]

sorted(users,key=lambda u: u,user_id)
  File "<ipython-input-14-5c8fe9ed8fad>", line 1
    sorted(users,key=lambda u: u,user_id)
                                ^
SyntaxError: positional argument follows keyword argument




sorted(users,key=lambda u: u.user_id)
Out[15]: [User(3), User(23), User(99)]

from operator import attrgetter

sorted(users,key=attrgetter('user_id'))
Out[17]: [User(3), User(23), User(99)]

min(user,key=attrgetter('user_name'))
Traceback (most recent call last):

  File "<ipython-input-18-9a9e70eb7113>", line 1, in <module>
    min(user,key=attrgetter('user_name'))

NameError: name 'user' is not defined




min(usesr,key=attrgetter('user_name'))
Traceback (most recent call last):

  File "<ipython-input-19-f83322a96f15>", line 1, in <module>
    min(usesr,key=attrgetter('user_name'))

NameError: name 'usesr' is not defined




min(users,key=attrgetter('user_name'))
Traceback (most recent call last):

  File "<ipython-input-20-2de890a3f6ee>", line 1, in <module>
    min(users,key=attrgetter('user_name'))

AttributeError: 'User' object has no attribute 'user_name'




min(users,key=attrgetter('user_id'))
Out[21]: User(3)

man(users,key=attrgetter('user_id'))
Traceback (most recent call last):

  File "<ipython-input-22-95390105d206>", line 1, in <module>
    man(users,key=attrgetter('user_id'))

NameError: name 'man' is not defined




max(users,key=attrgetter('user_id'))
Out[23]: User(99)

rows=[
{'address':'5412 CLARK','date':'07/01/2012'},
{'address':'1412 CLARK','date':'07/01/2016'},
{'address':'2412 CLARK','date':'07/01/2019'}]

from operator import itemgetter

from itertools import groupby

row.sort(key=itemgetter('data'))
Traceback (most recent call last):

  File "<ipython-input-27-ffe702f8eb0d>", line 1, in <module>
    row.sort(key=itemgetter('data'))

NameError: name 'row' is not defined




rows.sort(key=itemgetter('data'))
Traceback (most recent call last):

  File "<ipython-input-28-ded3f87680e0>", line 1, in <module>
    rows.sort(key=itemgetter('data'))

KeyError: 'data'




rows.sort(key=itemgetter('date'))

rows
Out[30]: 
[{'address': '5412 CLARK', 'date': '07/01/2012'},
 {'address': '1412 CLARK', 'date': '07/01/2016'},
 {'address': '2412 CLARK', 'date': '07/01/2019'}]

from date,items in groupby(rows,key=itemgetter('date')):
    print(date)
  File "<ipython-input-31-ded8b3e4eaf1>", line 1
    from date,items in groupby(rows,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows,key=itemgetter('date')):
    print(date)/
  File "<ipython-input-32-4dd3b05cfc92>", line 1
    from date,items in groupby(rows,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows,key=itemgetter('date'))
    print(date)\
    for i in items:
        print('  ',i)
  File "<ipython-input-33-e9dafca7d617>", line 1
    from date,items in groupby(rows,key=itemgetter('date'))
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows ,key=itemgetter('date'))
    print(date)\ 
    for i in items:
        print('  ',i)
  File "<ipython-input-34-d2edb808cae3>", line 1
    from date,items in groupby(rows ,key=itemgetter('date'))
             ^
SyntaxError: invalid syntax




runfile('C:/Users/16476/untitled0.py', wdir='C:/Users/16476')
Traceback (most recent call last):

  File "d:\Users\16476\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-35-a188ba00e4e9>", line 1, in <module>
    runfile('C:/Users/16476/untitled0.py', wdir='C:/Users/16476')

  File "d:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "d:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/16476/untitled0.py", line 9
    print('  ',i)
                 
^
SyntaxError: EOF while scanning triple-quoted string literal




from date,items in groupby(rows ,key=itemgetter('date')):
    print(date)\ 
    for i in items:
        print('  ',i)
  File "<ipython-input-36-665a94da095b>", line 1
    from date,items in groupby(rows ,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows,key=itemgetter('date')):
    print(date)\
    for i in items:
        print('  ',i)
  File "<ipython-input-37-98ac19b98562>", line 1
    from date,items in groupby(rows,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




for date,items in groupby(rows,key=itemgetter('date')):
    print(date)\
    for i in items:
        print('  ',i)
  File "<ipython-input-38-043ef2cbeca1>", line 3
    for i in items:
      ^
SyntaxError: invalid syntax




for date,items in groupby(rows,key=itemgetter('date')):
    print(date)
    for i in items:
        print('  ',i) 
        
07/01/2012
   {'address': '5412 CLARK', 'date': '07/01/2012'}
07/01/2016
   {'address': '1412 CLARK', 'date': '07/01/2016'}
07/01/2019
   {'address': '2412 CLARK', 'date': '07/01/2019'}
 from collections import namedtuple

s=namedtuple('S',['A''B'])

s=namedtuple('Sb',['A''B'])

s
Out[49]: __main__.Sb

sb
Traceback (most recent call last):

  File "<ipython-input-50-2e29fd6b6233>", line 1, in <module>
    sb

NameError: name 'sb' is not defined




Sb
Traceback (most recent call last):

  File "<ipython-input-51-09d66f3f1d43>", line 1, in <module>
    Sb

NameError: name 'Sb' is not defined




sub=s('c','d')
Traceback (most recent call last):

  File "<ipython-input-52-b9ab37554950>", line 1, in <module>
    sub=s('c','d')

TypeError: __new__() takes 2 positional arguments but 3 were given




s=namedtuple('s',['A''B'])

sc=s('c','d')
Traceback (most recent call last):

  File "<ipython-input-54-c37c11b9961a>", line 1, in <module>
    sc=s('c','d')

TypeError: __new__() takes 2 positional arguments but 3 were given




sc=('c')

sc
Out[56]: 'c'

sc=s('s')

sc
Out[58]: s(AB='s')

import numpy as np

np.random.randint(10,size=10)
Out[60]: array([7, 7, 3, 7, 3, 5, 0, 2, 4, 4])

a=np.random.randint(10,size=10)

a
Out[62]: array([9, 2, 9, 1, 3, 8, 6, 6, 7, 0])

s=sum(a)

s
Out[64]: 51

s=sum(x**x for x in a)

s
Out[66]: 792535082

   



import os

file=os.listdir('dirname')
Traceback (most recent call last):

  File "<ipython-input-68-ffd0d57c2f8d>", line 1, in <module>
    file=os.listdir('dirname')

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'dirname'




file=os.listdir('%dirs')
Traceback (most recent call last):

  File "<ipython-input-69-73428e3e7cb8>", line 1, in <module>
    file=os.listdir('%dirs')

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '%dirs'




file=os.listdir()

file
Out[71]: 
['.anaconda',
 '.android',
 '.AndroidStudio3.2',
 '.bash_history',
 '.BigNox',
 '.conda',
 '.condarc',
 '.config',
 '.emulator_console_auth_token',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipython',
 '.LdVirtualBox',
 '.matplotlib',
 '.spyder-py3',
 '.ssh',
 '.VirtualBox',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'd4ac4633ebd6440fa397b84f1bc94a3c.7z',
 'Favorites',
 'Foxit Reader SDK ActiveX.ini',
 'Hello.java',
 'inittk.ini',
 'inst.ini',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'Nox_share',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{acf20663-1ba4-11e8-83d4-f894c2bd03de}.TM.blf',
 'NTUSER.DAT{acf20663-1ba4-11e8-83d4-f894c2bd03de}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{acf20663-1ba4-11e8-83d4-f894c2bd03de}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'ntuser.pol',
 'nuuid.ini',
 'Pictures',
 'pip',
 'PrintHood',
 'python123demo',
 'Recent',
 'Saved Games',
 'scikit_learn_data',
 'Searches',
 'SendTo',
 'skb.kc',
 'source',
 'Templates',
 'UnblockNeteaseMusic-master',
 'untitled0.py',
 'useruid.ini',
 'Videos',
 'VirtualBox VMs',
 'vmlogs',
 '「开始」菜单']

s=('acme'50,,123.45)
  File "<ipython-input-72-d18d344791bb>", line 1
    s=('acme'50,,123.45)
              ^
SyntaxError: invalid syntax




s=('acme',50,123.45)

print(','.join(str(x) for x in s))
acme,50,123.45

a={'x':1'y':2}
  File "<ipython-input-75-f88a488f0b98>", line 1
    a={'x':1'y':2}
              ^
SyntaxError: invalid syntax




a={'x':1,'y':2}

a
Out[77]: {'x': 1, 'y': 2}

b={'y':3,'z':4}

from collections import ChainMap

c=ChainMap(a,b)

c
Out[81]: ChainMap({'x': 1, 'y': 2}, {'y': 3, 'z': 4})

--------第二章--------

re.split(r'[;,\s]\s*',line)
Out[85]: ['kaja', 'kaefj', 'aekl', 'eaklf', 'fff']

filename='scji.py'

filename.endswith('txt')
Out[87]: False

s='{name} is {f}'

s.format(name='fish',f='me')
Out[276]: 'fish is me'

name='i'

f='fish'

s.format_map(vars())
Out[279]: 'i is fish'

class Info:
    def __init__(self,name,f):
        self.name=name
        self.f=f
        

a=info(10,4)
Traceback (most recent call last):

  File "<ipython-input-281-a0dd896fa1fa>", line 1, in <module>
    a=info(10,4)

NameError: name 'info' is not defined




a=Info(10,4)

a
Out[283]: <__main__.Info at 0x2504b8ef248>

s.format_map(vars(a))
Out[284]: '10 is 4'

s.format(name=0)
Traceback (most recent call last):

  File "<ipython-input-285-cffadfed4ad8>", line 1, in <module>
    s.format(name=0)

KeyError: 'f'

textwrap.fill(s,77)
Out[315]: '我是一段很长很长很长的长字符，以至于我得转义换行，接着再换行'

textwrap.fill(s,3)
Out[316]: '我是一\n段很长\n很长很\n长的长\n字符，\n以至于\n我得转\n义换行\n，接着\n再换行'

print(textwrap.fill(s,3))
我是一
段很长
很长很
长的长
字符，
以至于
我得转
义换行
，接着
再换行

print(textwrap.fill(s,10,initial_indent=' '))
 我是一段很长很长很
长的长字符，以至于我
得转义换行，接着再换
行

print(textwrap.fill(s,10))
我是一段很长很长很长
的长字符，以至于我得
转义换行，接着再换行

print(textwrap.fill(s,10,subsequent_indent=' '))
我是一段很长很长很长
 的长字符，以至于我
 得转义换行，接着再
 换行

import os

os.get_terminal_size().columns
Traceback (most recent call last):

  File "<ipython-input-322-863e08fd3df5>", line 1, in <module>
    os.get_terminal_size().columns

OSError: [WinError 6] 句柄无效。




os.get_terminal_size().columns
Traceback (most recent call last):

  File "<ipython-input-323-863e08fd3df5>", line 1, in <module>
    os.get_terminal_size().columns

OSError: [WinError 6] 句柄无效。




s='<html>haha</html>'

import html

html.escape(s)
Out[326]: '&lt;html&gt;haha&lt;/html&gt;'

s.encode('ascii')
Out[327]: b'<html>haha</html>'

text='foo
  File "<ipython-input-328-6550bbabdd60>", line 1
    text='foo
             ^
SyntaxError: EOL while scanning string literal




text='foo=23+42*10'

import re

NAME=r'?P<NAME>[[a-zA-Z_0-9]*)'

NAME=r'?P<NAME>[[a-zA-Z_][a-zA-Z_0-9]*)'

NUM=r'(?P<NUM>\d+)'

PLUS=r'(?P<PLUS>\d+)'

PLUS=r'(?P<PLUS>\+)'

TIMES=r'(？P<TIMES>\*)'

EQ=r'(?P<EQ>=)'

WS=r'(?P<WS>\s+)'

master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))
Traceback (most recent call last):

  File "<ipython-input-339-7165229117c2>", line 1, in <module>
    master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))

  File "d:\Users\16476\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))

error: nothing to repeat




NAME=r'?P<NAME>[a-zA-Z_][a-zA-Z_0-9]*)'

master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))
Traceback (most recent call last):

  File "<ipython-input-341-7165229117c2>", line 1, in <module>
    master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))

  File "d:\Users\16476\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))

error: nothing to repeat




TIMES=r'(?P<TIMES>\*)'

master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))
Traceback (most recent call last):

  File "<ipython-input-343-7165229117c2>", line 1, in <module>
    master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))

  File "d:\Users\16476\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))

error: nothing to repeat




'|'.join([NAME,NUM,PLUS,TIMES,EQ,WS])
Out[344]: '?P<NAME>[a-zA-Z_][a-zA-Z_0-9]*)|(?P<NUM>\\d+)|(?P<PLUS>\\+)|(?P<TIMES>\\*)|(?P<EQ>=)|(?P<WS>\\s+)'

rec='|'.join([NAME,NUM,PLUS,TIMES,EQ,WS])

re=re.compile(rec)
Traceback (most recent call last):

  File "<ipython-input-346-dbe4bd3b4a4d>", line 1, in <module>
    re=re.compile(rec)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))

error: nothing to repeat




NAME = r'(?P<NAME>[a-zA-Z_][a-zA-Z_0-9]*)'
NUM = r'(?P<NUM>\d+)'
PLUS = r'(?P<PLUS>\+)'
TIMES = r'(?P<TIMES>\*)'
EQ = r'(?P<EQ>=)'
WS = r'(?P<WS>\s+)'

master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))

rec='|'.join([NAME,NUM,PLUS,TIMES,EQ,WS])

rec
Out[350]: '(?P<NAME>[a-zA-Z_][a-zA-Z_0-9]*)|(?P<NUM>\\d+)|(?P<PLUS>\\+)|(?P<TIMES>\\*)|(?P<EQ>=)|(?P<WS>\\s+)'

scanner=master_pat('foo= 42')
Traceback (most recent call last):

  File "<ipython-input-351-8c5fb04b62db>", line 1, in <module>
    scanner=master_pat('foo= 42')

TypeError: 're.Pattern' object is not callable




scanner=master_pat.scanner('foo= 42')

scanner.match
Out[353]: <function SRE_Scanner.match()>

scanner.match()
Out[354]: <re.Match object; span=(0, 3), match='foo'>

_.lastgroup,_.group()
Out[355]: ('NAME', 'foo')

_.lastgroup,_.group()
Traceback (most recent call last):

  File "<ipython-input-356-41a1219e790e>", line 1, in <module>
    _.lastgroup,_.group()

AttributeError: 'tuple' object has no attribute 'lastgroup'




scanner.match()
Out[357]: <re.Match object; span=(3, 4), match='='>

_.lastgroup,_.group()
Out[358]: ('EQ', '=')

_.lastgroup,_.group()
Traceback (most recent call last):

  File "<ipython-input-359-41a1219e790e>", line 1, in <module>
    _.lastgroup,_.group()

AttributeError: 'tuple' object has no attribute 'lastgroup'




scanner.match()
Out[360]: <re.Match object; span=(4, 5), match=' '>

_.lastgroup,_.group()
Out[361]: ('WS', ' ')

scanner.match()
Out[362]: <re.Match object; span=(5, 7), match='42'>

_.lastgroup,_.group()
Out[363]: ('NUM', '42')

scanner.match()

from collections import  namedtuple

Token=namedtuple('Token',['type','value'])

def generate_tokens(pat,text):
    scanner=pat.scanner(text)
    for m in iter(scanner.match,None):
        yield Token(m.lastgroup,m.group())
        

for tok in generate_tokens(master_pat,'foo= 33+22'):
    print(tok)
    
Token(type='NAME', value='foo')
Token(type='EQ', value='=')
Token(type='WS', value=' ')
Token(type='NUM', value='33')
Token(type='PLUS', value='+')
Token(type='NUM', value='22')